version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 1000:1000
    ports:
      - 80:80
    volumes:
      - ${HOME_PATH}:/data
      - ${FB_CONFIG_PATH}:/config
    restart: unless-stopped
    #security_opt: 
    #- no-new-privleges:true
